### ISSUE TITLE
结果精度问题

### ISSUE THREAD

**Issue by huangwentao123** [WenkeHuang/RethinkFL#2]
您好，最近在阅读您的论文和代码，做了一些复现工作。
使用最近的版本代码，数据集是从您公开的url下载的
发现默认参数在office上表现良好，但数字识别中 ，精度不高
```
The 94 Communcation Accuracy: 71.388 Method: fpl
[97.2, 90.68, 62.3, 35.37]
```
请问有哪些需要注意的地方吗？代码没有改动
不好意思打扰您了

**Comment by huangwentao123** [comment]
有可能是 您代码最后跑的是office任务，`--parti_num`为10
刚刚注意到论文里  数字 任务 --parti_num为20 
可能是这个原因

**Comment by huangwentao123** [comment]
--parti_num 设置为20 后报错
`Traceback (most recent call last):
  File "main.py", line 105, in <module>
    main()
  File "main.py", line 101, in main
    train(model, priv_dataset, args)
  File "/root/hwt/RethinkFL/utils/training.py", line 97, in train
    epoch_loc_loss_dict = model.loc_update(pri_train_loaders)
  File "/root/hwt/RethinkFL/models/fpl.py", line 129, in loc_update
    self._train_net(i, self.nets_list[i], priloader_list[i])
  File "/root/hwt/RethinkFL/models/fpl.py", line 176, in _train_net
    loss_instance = self.hierarchical_info_loss(f_now, label, all_f, mean_f, all_global_protos_keys)
  File "/root/hwt/RethinkFL/models/fpl.py", line 91, in hierarchical_info_loss
    f_pos = np.array(all_f)[all_global_protos_keys == label.item()][0].to(self.device)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part`

**Comment by byf01** [comment]
你好，请问office数据集也是在作者公开的url下载的吗，google网盘里貌似只有digits数据集。
